import { Skill, Job, Education, Social } from "./models/models";

export const work_experiences: Job[] = [
  {
    company: "Konrad Group",
    position: "Software Developer",
    description: null,
    jobDescription:
      "In Konrad, I was a full stack software engineer performing different tasks throughout different projects in the banking and transportation industries. The main tech stack that I used in these projects was Adobe Experience Manager with Java in the backend and React in the frontend.  I was in charge of different tasks depending on the project, such as maintenance, deployments for different websites, migrations from older versions of AEM to AEM cloud, and from JavaScript to Typescript in other projects. ",
    from: new Date("2021-09-14"),
    to: new Date("2023-05-15"),
    skills: [1, 2, 3, 4, 8, 9, 11, 12],
    assets: [
      "https://i.imgur.com/dF8n3Ha.png",
      "https://i.imgur.com/kQKp9lN.png",
      "https://i.imgur.com/w5iedq5.png",
      "https://i.imgur.com/ug1NMYj.png",
    ],
    urls: [],
  },
  {
    company: "Solasystem (Contract) ",
    position: "Frontend Developer",
    description:
      "Solasytem.io was a hub where different users could check out the projects made in the Solana network, as well as submit their own projects and information so others can visit their website and share interests in Solana. Unfortunately the site is no longer online.",
    jobDescription:
      "In SolaSystem I was in charge of developing the frontend of the website. The website and project was built rather quickly and efficiently, and it connected with the SQL databases built by us during the duration of the project. As well as showing graphs and information of the current Solana prices real-time.",
    from: new Date("2021-03-02"),
    to: new Date("2021-03-02"),
    skills: [2, 3, 5, 11],
    assets: [
      "https://i.imgur.com/KMNr7o7.png",
      "https://i.imgur.com/3E2LkJJ.png",
      "https://i.imgur.com/NEKAoWS.png",
      "https://i.imgur.com/KhLECt1.png",
    ],
    urls: [
      {
        name: "Twitter.com/sola_system",
        url: "https://twitter.com/Sola_System",
      },
    ],
  },
  {
    company: "5Dimes",
    position: "Customer Service Associate",
    description: null,
    jobDescription:
      "In 5Dimes, I worked as a customer service agent handling questions that customers had about their accounts, payments, deposits , wagers, technical issues and general questions. I was a high performer, with a high satisfaction rate, and had customers frequently asking for me to provide support specifically from them, as well as providing non-mandatory follow-ups to go the extra mile on each interaction.",
    from: new Date("2018-10-02"),
    to: new Date("2020-09-30"),
    skills: [],
    assets: [],
    urls: [],
  },
  {
    company: "Concentrix",
    position: "Tech Support Associate",
    description: null,
    jobDescription:
      "In Concentrix, I was a customer service and tech support agent that helped customers in one of the most popular and powerful mobile operating systems in the industry. I was in charge of guiding customers through known and , sometimes, unique problems with their mobile phones. I was a high performer throughout the years that I was there with a high customer satisfaction rate, as well as helping agents as a floor support.",
    from: new Date("2018-05-02"),
    to: new Date("2020-08-02"),
    skills: [],
    assets: [],
    urls: [],
  },
];

export const education: Education[] = [
  {
    institution: "Cenfotec University",
    degree: "Web Design and Web Development Technical Degree",
    from: new Date("2018-01-01"),
    to: new Date("2020-12-30"),
    skills: [1, 2, 3, 4, 5, 6, 7, 8, 10, 11],
  },
  {
    institution: "Brain Station",
    degree: "Web Development Immersive Program",
    from: new Date("2021-06-01"),
    to: new Date("2020-12-30"),
    skills: [2, 3, 4, 8, 11],
  },
];

export const skills: Skill[] = [
  { id: "1", name: "Typescript" },
  { id: "2", name: "React" },
  { id: "3", name: "JavaScript" },
  { id: "4", name: "AEM" },
  { id: "5", name: "NodeJS" },
  { id: "6", name: "Photoshop" },
  { id: "7", name: "MongoDB" },
  { id: "8", name: "Java" },
  { id: "9", name: "Figma" },
  { id: "10", name: "Angular" },
  { id: "11", name: " CSS" },
  { id: "12", name: " JIRA" },
];

export function getSkillById(skillId: number): string {
  var result: any = skills.filter((skill) => {
    return skill.id === skillId.toString();
  });

  return result[0].name;
}

export const images = [
  {
    id: "0",
    title: "Warsaw Image #1",
    categories: [],
    src: "https://i.imgur.com/53lcHQU.jpg",
    cityId: "14",
  },
  {
    id: "1",
    title: "Warsaw Image #2",
    categories: [],
    src: "https://i.imgur.com/NvJBfI2.jpg",
    cityId: "14",
  },
  {
    id: "2",
    title: "Warsaw Image #3",
    categories: [],
    src: "https://i.imgur.com/R8kDLOK.jpg",
    cityId: "14",
  },
  {
    id: "3",
    title: "Warsaw Image #4",
    categories: [],
    src: "https://i.imgur.com/u0zttvO.jpg",
    cityId: "14",
  },
  {
    id: "4",
    title: "Warsaw Image #5",
    categories: [],
    src: "https://i.imgur.com/yTcqLz8.jpg",
    cityId: "14",
  },
  {
    id: "5",
    title: "Warsaw Image #6",
    categories: [],
    src: "https://i.imgur.com/gkoEOkN.jpg",
    cityId: "14",
  },
  {
    id: "6",
    title: "Warsaw Image #7",
    categories: [],
    src: "https://i.imgur.com/iPmxwqq.jpg",
    cityId: "14",
  },
  {
    id: "7",
    title: "Warsaw Image #8",
    categories: [],
    src: "https://i.imgur.com/dkbH1mo.jpg",
    cityId: "14",
  },
  {
    id: "8",
    title: "Warsaw Image #9",
    categories: [],
    src: "https://i.imgur.com/NjE6Bwo.jpg",
    cityId: "14",
  },
  {
    id: "9",
    title: "Warsaw Image #10",
    categories: [],
    src: "https://i.imgur.com/Kklrqaf.jpg",
    cityId: "14",
  },
  {
    id: "10",
    title: "Warsaw Image #11",
    categories: [],
    src: "https://i.imgur.com/ZcAdlbK.jpg",
    cityId: "14",
  },
  {
    id: "11",
    title: "Warsaw Image #12",
    categories: [],
    src: "https://i.imgur.com/5XF8TFo.jpg",
    cityId: "14",
  },
  {
    id: "12",
    title: "Warsaw Image #13",
    categories: [],
    src: "https://i.imgur.com/0f612Xk.jpg",
    cityId: "14",
  },
  {
    id: "13",
    title: "Warsaw Image #14",
    categories: [],
    src: "https://i.imgur.com/yW4hEwY.jpg",
    cityId: "14",
  },
  {
    id: "14",
    title: "Warsaw Image #15",
    categories: [],
    src: "https://i.imgur.com/qPW75Ok.jpg",
    cityId: "14",
  },
  {
    id: "15",
    title: "Warsaw Image #16",
    categories: [],
    src: "https://i.imgur.com/vhXYEGM.jpg",
    cityId: "14",
  },
  {
    id: "16",
    title: "Warsaw Image #17",
    categories: [],
    src: "https://i.imgur.com/lw5T7wa.jpg",
    cityId: "14",
  },
  {
    id: "17",
    title: "Warsaw Image #18",
    categories: [],
    src: "https://i.imgur.com/yayrxib.jpg",
    cityId: "14",
  },
  {
    id: "18",
    title: "Warsaw Image #19",
    categories: [],
    src: "https://i.imgur.com/08FPaLy.jpg",
    cityId: "14",
  },
  {
    id: "19",
    title: "Warsaw Image #20",
    categories: [],
    src: "https://i.imgur.com/5RQpMyI.jpg",
    cityId: "14",
  },
  {
    id: "20",
    title: "Warsaw Image #21",
    categories: [],
    src: "https://i.imgur.com/sQk4ANc.jpg",
    cityId: "14",
  },
  {
    id: "21",
    title: "Warsaw Image #22",
    categories: [],
    src: "https://i.imgur.com/kKhzOJz.jpg",
    cityId: "14",
  },
  {
    id: "22",
    title: "Warsaw Image #23",
    categories: [],
    src: "https://i.imgur.com/HOumDqQ.jpg",
    cityId: "14",
  },
  {
    id: "23",
    title: "Warsaw Image #24",
    categories: [],
    src: "https://i.imgur.com/Nsuy1dN.jpg",
    cityId: "14",
  },
  {
    id: "24",
    title: "Warsaw Image #25",
    categories: [],
    src: "https://i.imgur.com/EHtCnOW.jpg",
    cityId: "14",
  },
  {
    id: "25",
    title: "Warsaw Image #26",
    categories: [],
    src: "https://i.imgur.com/o2SDuvI.jpg",
    cityId: "14",
  },
  {
    id: "26",
    title: "Warsaw Image #27",
    categories: [],
    src: "https://i.imgur.com/UblC4sX.jpg",
    cityId: "14",
  },
  {
    id: "27",
    title: "Warsaw Image #28",
    categories: [],
    src: "https://i.imgur.com/CNmYQl1.jpg",
    cityId: "14",
  },
  {
    id: "28",
    title: "Warsaw Image #29",
    categories: [],
    src: "https://i.imgur.com/8TqEZ4w.jpg",
    cityId: "14",
  },
  {
    id: "29",
    title: "Warsaw Image #30",
    categories: [],
    src: "https://i.imgur.com/ThmVWql.jpg",
    cityId: "14",
  },
  {
    id: "30",
    title: "Warsaw Image #31",
    categories: [],
    src: "https://i.imgur.com/8oBokOg.jpg",
    cityId: "14",
  },
  {
    id: "31",
    title: "Warsaw Image #32",
    categories: [],
    src: "https://i.imgur.com/RVhXck5.jpg",
    cityId: "14",
  },
  {
    id: "32",
    title: "Warsaw Image #33",
    categories: [],
    src: "https://i.imgur.com/n9hzC1X.jpg",
    cityId: "14",
  },
  {
    id: "33",
    title: "Warsaw Image #34",
    categories: [],
    src: "https://i.imgur.com/eMQHQu3.jpg",
    cityId: "14",
  },
  {
    id: "34",
    title: "Warsaw Image #35",
    categories: [],
    src: "https://i.imgur.com/iq8shkj.jpg",
    cityId: "14",
  },
  {
    id: "35",
    title: "Warsaw Image #36",
    categories: [],
    src: "https://i.imgur.com/8euC0Cc.jpg",
    cityId: "14",
  },
  {
    id: "36",
    title: "Warsaw Image #37",
    categories: [],
    src: "https://i.imgur.com/E77omZK.jpg",
    cityId: "14",
  },
  {
    id: "37",
    title: "Warsaw Image #38",
    categories: [],
    src: "https://i.imgur.com/qgkobNc.jpg",
    cityId: "14",
  },
  {
    id: "38",
    title: "Warsaw Image #39",
    categories: [],
    src: "https://i.imgur.com/kHdAuIj.jpg",
    cityId: "14",
  },
  {
    id: "39",
    title: "Warsaw Image #40",
    categories: [],
    src: "https://i.imgur.com/adfsViy.jpg",
    cityId: "14",
  },
  {
    id: "40",
    title: "Warsaw Image #41",
    categories: [],
    src: "https://i.imgur.com/3fJ6fJa.jpg",
    cityId: "14",
  },
  {
    id: "41",
    title: "Warsaw Image #42",
    categories: [],
    src: "https://i.imgur.com/vlfn8rS.jpg",
    cityId: "14",
  },
  {
    id: "42",
    title: "Warsaw Image #43",
    categories: [],
    src: "https://i.imgur.com/VWCO22Y.jpg",
    cityId: "14",
  },
  {
    id: "43",
    title: "Warsaw Image #44",
    categories: [],
    src: "https://i.imgur.com/TWcxLPJ.jpg",
    cityId: "14",
  },
  {
    id: "44",
    title: "Warsaw Image #45",
    categories: [],
    src: "https://i.imgur.com/gqvCaPZ.jpg",
    cityId: "14",
  },
  {
    id: "45",
    title: "Warsaw Image #46",
    categories: [],
    src: "https://i.imgur.com/1LiBw1V.jpg",
    cityId: "14",
  },
  {
    id: "46",
    title: "Warsaw Image #47",
    categories: [],
    src: "https://i.imgur.com/qRsX2Cz.jpg",
    cityId: "14",
  },
  {
    id: "47",
    title: "Warsaw Image #48",
    categories: [],
    src: "https://i.imgur.com/JzwLbgV.jpg",
    cityId: "14",
  },
  {
    id: "48",
    title: "Warsaw Image #49",
    categories: [],
    src: "https://i.imgur.com/zqhgG4u.jpg",
    cityId: "14",
  },
  {
    id: "49",
    title: "Warsaw Image #50",
    categories: [],
    src: "https://i.imgur.com/9fpREtZ.jpg",
    cityId: "14",
  },
  {
    id: "50",
    title: "Warsaw Image #51",
    categories: [],
    src: "https://i.imgur.com/ufuYCp7.jpg",
    cityId: "14",
  },
  {
    id: "51",
    title: "Warsaw Image #52",
    categories: [],
    src: "https://i.imgur.com/hPX4cWL.jpg",
    cityId: "14",
  },
  {
    id: "52",
    title: "Warsaw Image #53",
    categories: [],
    src: "https://i.imgur.com/TtnSNYz.jpg",
    cityId: "14",
  },
  {
    id: "53",
    title: "Warsaw Image #54",
    categories: [],
    src: "https://i.imgur.com/YFquhNU.jpg",
    cityId: "14",
  },
  {
    id: "54",
    title: "Warsaw Image #55",
    categories: [],
    src: "https://i.imgur.com/eJT3B9G.jpg",
    cityId: "14",
  },
  {
    id: "55",
    title: "Warsaw Image #56",
    categories: [],
    src: "https://i.imgur.com/EFGjnaG.jpg",
    cityId: "14",
  },
  {
    id: "56",
    title: "Warsaw Image #57",
    categories: [],
    src: "https://i.imgur.com/XQnFW6Z.jpg",
    cityId: "14",
  },
  {
    id: "57",
    title: "Warsaw Image #58",
    categories: [],
    src: "https://i.imgur.com/wmHZ7Ws.jpg",
    cityId: "14",
  },
  {
    id: "58",
    title: "Warsaw Image #59",
    categories: [],
    src: "https://i.imgur.com/N3ceE2I.jpg",
    cityId: "14",
  },
  {
    id: "59",
    title: "Warsaw Image #60",
    categories: [],
    src: "https://i.imgur.com/wEtwd25.jpg",
    cityId: "14",
  },
  {
    id: "60",
    title: "Warsaw Image #61",
    categories: [],
    src: "https://i.imgur.com/R5gsrIW.jpg",
    cityId: "14",
  },
  {
    id: "61",
    title: "Warsaw Image #62",
    categories: [],
    src: "https://i.imgur.com/SgsvCuw.jpg",
    cityId: "14",
  },
  {
    id: "62",
    title: "Warsaw Image #63",
    categories: [],
    src: "https://i.imgur.com/R0IUaZL.jpg",
    cityId: "14",
  },
  {
    id: "63",
    title: "Warsaw Image #64",
    categories: [],
    src: "https://i.imgur.com/X30sPU8.jpg",
    cityId: "14",
  },
  {
    id: "64",
    title: "Warsaw Image #65",
    categories: [],
    src: "https://i.imgur.com/8AbsQbZ.jpg",
    cityId: "14",
  },
  {
    id: "65",
    title: "Warsaw Image #66",
    categories: [],
    src: "https://i.imgur.com/c4SbtpC.jpg",
    cityId: "14",
  },
  {
    id: "66",
    title: "Warsaw Image #67",
    categories: [],
    src: "https://i.imgur.com/g6eiI8V.jpg",
    cityId: "14",
  },
  {
    id: "67",
    title: "Warsaw Image #68",
    categories: [],
    src: "https://i.imgur.com/SCFNBxW.jpg",
    cityId: "14",
  },
  {
    id: "68",
    title: "Warsaw Image #69",
    categories: [],
    src: "https://i.imgur.com/alKL3p9.jpg",
    cityId: "14",
  },
  {
    id: "69",
    title: "Warsaw Image #70",
    categories: [],
    src: "https://i.imgur.com/wRiM8v0.jpg",
    cityId: "14",
  },
  {
    id: "70",
    title: "Warsaw Image #71",
    categories: [],
    src: "https://i.imgur.com/HiHf3q2.jpg",
    cityId: "14",
  },
  {
    id: "71",
    title: "Warsaw Image #72",
    categories: [],
    src: "https://i.imgur.com/GEUW9gG.jpg",
    cityId: "14",
  },
  {
    id: "72",
    title: "Warsaw Image #73",
    categories: [],
    src: "https://i.imgur.com/dkVcP3b.jpg",
    cityId: "14",
  },
  {
    id: "73",
    title: "Warsaw Image #74",
    categories: [],
    src: "https://i.imgur.com/rsSnL4F.jpg",
    cityId: "14",
  },
  {
    id: "74",
    title: "Warsaw Image #75",
    categories: [],
    src: "https://i.imgur.com/DOdqEsB.jpg",
    cityId: "14",
  },
  {
    id: "75",
    title: "Warsaw Image #76",
    categories: [],
    src: "https://i.imgur.com/m6UuqlV.jpg",
    cityId: "14",
  },
  {
    id: "76",
    title: "Warsaw Image #77",
    categories: [],
    src: "https://i.imgur.com/EzNcN3N.jpg",
    cityId: "14",
  },
  {
    id: "77",
    title: "Warsaw Image #78",
    categories: [],
    src: "https://i.imgur.com/M7Z06VG.jpg",
    cityId: "14",
  },
  {
    id: "78",
    title: "Warsaw Image #79",
    categories: [],
    src: "https://i.imgur.com/rJRVY0W.jpg",
    cityId: "14",
  },
  {
    id: "79",
    title: "Warsaw Image #80",
    categories: [],
    src: "https://i.imgur.com/BeHQuq3.jpg",
    cityId: "14",
  },
  {
    id: "80",
    title: "Warsaw Image #81",
    categories: [],
    src: "https://i.imgur.com/OM2Jobj.jpg",
    cityId: "14",
  },
  {
    id: "81",
    title: "Warsaw Image #82",
    categories: [],
    src: "https://i.imgur.com/dLNyplR.jpg",
    cityId: "14",
  },
  {
    id: "82",
    title: "Warsaw Image #83",
    categories: [],
    src: "https://i.imgur.com/gl2QWBw.jpg",
    cityId: "14",
  },
  {
    id: "83",
    title: "Warsaw Image #84",
    categories: [],
    src: "https://i.imgur.com/ZcllKRZ.jpg",
    cityId: "14",
  },
  {
    id: "84",
    title: "Warsaw Image #85",
    categories: [],
    src: "https://i.imgur.com/PUBa2FP.jpg",
    cityId: "14",
  },
  {
    id: "85",
    title: "Warsaw Image #86",
    categories: [],
    src: "https://i.imgur.com/m9iGn9u.jpg",
    cityId: "14",
  },
  {
    id: "86",
    title: "Warsaw Image #87",
    categories: [],
    src: "https://i.imgur.com/mmzRKwX.jpg",
    cityId: "14",
  },
  {
    id: "87",
    title: "Warsaw Image #88",
    categories: [],
    src: "https://i.imgur.com/MbKeqLW.jpg",
    cityId: "14",
  },
  {
    id: "88",
    title: "Warsaw Image #89",
    categories: [],
    src: "https://i.imgur.com/0P2svqy.jpg",
    cityId: "14",
  },
  {
    id: "89",
    title: "Warsaw Image #90",
    categories: [],
    src: "https://i.imgur.com/4TFJvKQ.jpg",
    cityId: "14",
  },
];

export const socials: Social[] = [
  { name: "Github", url: "https://github.com/" },
  { name: "LinkedIn", url: "https://www.linkedin.com" },
];
